image: golang:latest

stages:
  - build

Build:
  stage: build
  script:
    - mkdir -p $GOPATH/src/github.com/bitspill/
    - cp -r $CI_PROJECT_DIR $GOPATH/src/github.com/bitspill/flod
    - mkdir bin
    - cd $GOPATH/src/github.com/bitspill/flod
    - GLIDE_TAG=v0.12.3
    - GLIDE_DOWNLOAD="https://github.com/Masterminds/glide/releases/download/$GLIDE_TAG/glide-$GLIDE_TAG-linux-amd64.tar.gz"
    - curl -L $GLIDE_DOWNLOAD | tar -xvz
    - export PATH=$PATH:$PWD/linux-amd64/
    - glide install
    - export GOBIN=$CI_PROJECT_DIR/bin
    - go install . ./cmd/...
    - cd $CI_PROJECT_DIR
    - ls bin
  artifacts:
    paths:
      - bin/addblock
      - bin/findcheckpoint
      - bin/floctl
      - bin/flod
      - bin/gencerts
